// <auto-generated />
using KoronaMetre.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace KoronaMetre.Migrations
{
    [DbContext(typeof(KoronaContextDb))]
    partial class KoronaContextDbModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.5")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("KoronaMetre.Models.KoronaBilgi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("OlumSayisi")
                        .HasColumnType("int");

                    b.Property<int>("UlkeId")
                        .HasColumnType("int");

                    b.Property<int>("VakaSayisi")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UlkeId")
                        .IsUnique();

                    b.ToTable("KoronaBilgileri");
                });

            modelBuilder.Entity("KoronaMetre.Models.Ulke", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<long>("Nufus")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("Ulkeler");
                });

            modelBuilder.Entity("KoronaMetre.Models.KoronaBilgi", b =>
                {
                    b.HasOne("KoronaMetre.Models.Ulke", "Ulke")
                        .WithOne("KoronaBilgi")
                        .HasForeignKey("KoronaMetre.Models.KoronaBilgi", "UlkeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ulke");
                });

            modelBuilder.Entity("KoronaMetre.Models.Ulke", b =>
                {
                    b.Navigation("KoronaBilgi");
                });
#pragma warning restore 612, 618
        }
    }
}
